#include "content/PetPackLoader.h"

#include <cstring>
#include <fstream>
#include <unordered_set>
#include <utility>

namespace nimvlets::content {

namespace {

// "NVPACK2" + a trailing NUL, exactly 8 bytes — see
// docs/ANIMATION_RUNTIME.md for the full format this reader implements.
// Block 05 bumps the format from "NVPACK1" (flat idle/click/passive
// fields) to "NVPACK2" (a named-state behavior graph) — a genuinely
// different shape, not an additive extension, so a new magic value is
// the honest choice instead of silently reinterpreting old bytes under
// the old name. Every pack this repo ships is regenerated by its own
// generate_<pet>_pack.py from source, so there is no external/shipped
// content that needs NVPACK1 read-compatibility.
constexpr char kMagic[8] = {'N', 'V', 'P', 'A', 'C', 'K', '2', '\0'};

// Bounds-checked cursor over an in-memory byte buffer — same contract
// as Block 02's original: every Read* method fails (and remembers the
// *first* failure reason) rather than reading past the end. Integers/
// floats are little-endian (matches tools/compile_pet_pack.py's
// struct.pack("<...")); every platform this project targets is
// little-endian, so no byte-swapping is implemented.
class ByteReader {
public:
    ByteReader(const std::uint8_t* data, std::size_t size) : data_(data), size_(size) {}

    bool ok() const { return ok_; }
    const std::string& Error() const { return error_; }

    bool ReadBytes(void* dst, std::size_t n) {
        if (!ok_) {
            return false;
        }
        if (n > size_ - pos_) {
            Fail("unexpected end of pack data");
            return false;
        }
        std::memcpy(dst, data_ + pos_, n);
        pos_ += n;
        return true;
    }

    bool ReadUint8(std::uint8_t& out) { return ReadBytes(&out, sizeof(out)); }
    bool ReadUint32(std::uint32_t& out) { return ReadBytes(&out, sizeof(out)); }
    bool ReadFloat64(double& out) { return ReadBytes(&out, sizeof(out)); }

    bool ReadString(std::string& out) {
        std::uint32_t len = 0;
        if (!ReadUint32(len)) {
            return false;
        }
        out.assign(static_cast<std::size_t>(len), '\0');
        if (len == 0) {
            return true;
        }
        return ReadBytes(out.data(), len);
    }

    bool ReadPixels(std::vector<std::uint8_t>& out, std::size_t n) {
        out.assign(n, 0);
        if (n == 0) {
            return true;
        }
        return ReadBytes(out.data(), n);
    }

    void Fail(const std::string& message) {
        if (ok_) {  // keep only the first failure — later ones are usually noise from it
            ok_ = false;
            error_ = message;
        }
    }

private:
    const std::uint8_t* data_;
    std::size_t size_;
    std::size_t pos_ = 0;
    bool ok_ = true;
    std::string error_;
};

bool ReadAnimation(ByteReader& reader, AnimationDefinition& anim, std::string& outError) {
    if (!reader.ReadString(anim.id)) {
        outError = reader.Error();
        return false;
    }

    std::uint8_t kindByte = 0;
    if (!reader.ReadUint8(kindByte)) {
        outError = reader.Error();
        return false;
    }
    if (kindByte > static_cast<std::uint8_t>(PlaybackKind::kOneShot)) {
        outError = "animation '" + anim.id + "': invalid playback kind byte " + std::to_string(static_cast<int>(kindByte));
        return false;
    }
    anim.kind = static_cast<PlaybackKind>(kindByte);

    if (!reader.ReadFloat64(anim.fps)) {
        outError = reader.Error();
        return false;
    }

    std::uint8_t returnsByte = 0;
    if (!reader.ReadUint8(returnsByte)) {
        outError = reader.Error();
        return false;
    }
    anim.returnsToIdle = returnsByte != 0;

    std::uint32_t frameCount = 0;
    if (!reader.ReadUint32(frameCount)) {
        outError = reader.Error();
        return false;
    }

    anim.frames.clear();
    anim.frames.reserve(frameCount);
    int firstWidth = -1;
    int firstHeight = -1;

    for (std::uint32_t i = 0; i < frameCount; ++i) {
        FrameDefinition frame;
        std::uint32_t w = 0;
        std::uint32_t h = 0;
        double anchorX = 0.0;
        double anchorY = 0.0;
        double durationMs = 0.0;
        if (!reader.ReadUint32(w) || !reader.ReadUint32(h) || !reader.ReadFloat64(anchorX) ||
            !reader.ReadFloat64(anchorY) || !reader.ReadFloat64(durationMs)) {
            outError = reader.Error();
            return false;
        }

        frame.width = static_cast<int>(w);
        frame.height = static_cast<int>(h);
        frame.anchor = core::Point{anchorX, anchorY};
        frame.durationMs = durationMs;

        if (firstWidth < 0) {
            firstWidth = frame.width;
            firstHeight = frame.height;
        } else if (frame.width != firstWidth || frame.height != firstHeight) {
            outError = "animation '" + anim.id + "': frame " + std::to_string(i) + " is " + std::to_string(frame.width) +
                       "x" + std::to_string(frame.height) + ", expected " + std::to_string(firstWidth) + "x" +
                       std::to_string(firstHeight) + " to match this animation's first frame";
            return false;
        }

        const std::size_t pixelBytes = static_cast<std::size_t>(w) * static_cast<std::size_t>(h) * 4;
        if (!reader.ReadPixels(frame.pixels, pixelBytes)) {
            outError = reader.Error();
            return false;
        }

        anim.frames.push_back(std::move(frame));
    }

    if (anim.frames.empty()) {
        outError = "animation '" + anim.id + "' has zero frames";
        return false;
    }

    return true;
}

bool ReadDirectionByte(ByteReader& reader, const std::string& context, Direction& outDirection, std::string& outError) {
    std::uint8_t directionByte = 0;
    if (!reader.ReadUint8(directionByte)) {
        outError = reader.Error();
        return false;
    }
    if (directionByte > static_cast<std::uint8_t>(Direction::kLeft)) {
        outError = context + ": invalid direction byte " + std::to_string(static_cast<int>(directionByte));
        return false;
    }
    outDirection = static_cast<Direction>(directionByte);
    return true;
}

bool ReadDirectionalOverrides(
    ByteReader& reader, const std::string& sectionName, std::vector<DirectionalAnimationOverride>& out, std::string& outError) {
    std::uint32_t count = 0;
    if (!reader.ReadUint32(count)) {
        outError = reader.Error();
        return false;
    }
    out.clear();
    out.reserve(count);
    for (std::uint32_t i = 0; i < count; ++i) {
        const std::string context = sectionName + "[" + std::to_string(i) + "]";
        DirectionalAnimationOverride override_;
        if (!ReadDirectionByte(reader, context, override_.direction, outError)) {
            return false;
        }
        if (!ReadAnimation(reader, override_.animation, outError)) {
            return false;
        }
        out.push_back(std::move(override_));
    }
    return true;
}

bool ReadWeightedActions(
    ByteReader& reader, const std::string& sectionName, std::vector<WeightedAction>& out, std::string& outError) {
    std::uint32_t count = 0;
    if (!reader.ReadUint32(count)) {
        outError = reader.Error();
        return false;
    }
    out.clear();
    out.reserve(count);
    for (std::uint32_t i = 0; i < count; ++i) {
        const std::string context = sectionName + "[" + std::to_string(i) + "]";
        WeightedAction action;
        if (!reader.ReadString(action.id)) {
            outError = reader.Error();
            return false;
        }
        if (!reader.ReadFloat64(action.weight)) {
            outError = reader.Error();
            return false;
        }
        if (!reader.ReadString(action.targetStateId)) {
            outError = reader.Error();
            return false;
        }
        if (!ReadAnimation(reader, action.animation, outError)) {
            return false;
        }
        if (!ReadDirectionalOverrides(reader, context + ".directionOverrides", action.directionOverrides, outError)) {
            return false;
        }
        out.push_back(std::move(action));
    }
    return true;
}

bool ReadState(ByteReader& reader, const std::string& context, BehaviorState& state, std::string& outError) {
    if (!reader.ReadString(state.id)) {
        outError = reader.Error();
        return false;
    }
    if (!ReadAnimation(reader, state.baseAnimation, outError)) {
        return false;
    }
    if (!ReadDirectionalOverrides(reader, context + ".baseAnimationDirectionOverrides", state.baseAnimationDirectionOverrides, outError)) {
        return false;
    }
    if (!reader.ReadFloat64(state.ambientIntervalSeconds)) {
        outError = reader.Error();
        return false;
    }
    if (!ReadWeightedActions(reader, context + ".ambientActions", state.ambientActions, outError)) {
        return false;
    }
    std::uint8_t hoverUsesAmbientByte = 0;
    if (!reader.ReadUint8(hoverUsesAmbientByte)) {
        outError = reader.Error();
        return false;
    }
    state.hoverUsesAmbientActions = hoverUsesAmbientByte != 0;
    if (!ReadWeightedActions(reader, context + ".hoverActions", state.hoverActions, outError)) {
        return false;
    }
    if (state.hoverUsesAmbientActions && !state.hoverActions.empty()) {
        outError = context + ": hoverUsesAmbientActions is true but hoverActions is also non-empty (ambiguous)";
        return false;
    }
    if (!ReadWeightedActions(reader, context + ".clickActions", state.clickActions, outError)) {
        return false;
    }
    return true;
}

// Valida que cada WeightedAction::targetStateId de `pet` referencie un
// id realmente presente en pet.states -- una vez que se sabe eso,
// AnimationController::FindStateIndex() nunca puede fallar en runtime.
bool ValidateTargetStateIds(const PetDefinition& pet, std::string& outError) {
    std::unordered_set<std::string> stateIds;
    for (const BehaviorState& state : pet.states) {
        stateIds.insert(state.id);
    }

    auto checkActions = [&](const std::vector<WeightedAction>& actions, const std::string& context) -> bool {
        for (const WeightedAction& action : actions) {
            if (stateIds.find(action.targetStateId) == stateIds.end()) {
                outError = context + ": targetStateId '" + action.targetStateId + "' does not match any state id";
                return false;
            }
        }
        return true;
    };

    for (const BehaviorState& state : pet.states) {
        if (!checkActions(state.ambientActions, "state '" + state.id + "'.ambientActions") ||
            !checkActions(state.hoverActions, "state '" + state.id + "'.hoverActions") ||
            !checkActions(state.clickActions, "state '" + state.id + "'.clickActions")) {
            return false;
        }
    }
    return true;
}

}  // namespace

bool LoadPetPackFromMemory(const std::uint8_t* data, std::size_t size, PetDefinition& outPet, std::string& outError) {
    ByteReader reader(data, size);

    char magic[8];
    if (!reader.ReadBytes(magic, sizeof(magic))) {
        outError = reader.Error();
        return false;
    }
    if (std::memcmp(magic, kMagic, sizeof(kMagic)) != 0) {
        outError = "not a valid pet pack (bad magic — expected NVPACK2)";
        return false;
    }

    PetDefinition pet;

    if (!reader.ReadString(pet.id) || !reader.ReadString(pet.displayName) || !reader.ReadString(pet.variantGroup)) {
        outError = reader.Error();
        return false;
    }

    std::uint32_t canvasWidth = 0;
    std::uint32_t canvasHeight = 0;
    if (!reader.ReadUint32(canvasWidth) || !reader.ReadUint32(canvasHeight)) {
        outError = reader.Error();
        return false;
    }
    pet.canvasWidth = static_cast<int>(canvasWidth);
    pet.canvasHeight = static_cast<int>(canvasHeight);

    if (!reader.ReadUint8(pet.alphaHitThreshold) || !reader.ReadFloat64(pet.visualScale) || !reader.ReadString(pet.contentVersion)) {
        outError = reader.Error();
        return false;
    }

    std::uint32_t stateCount = 0;
    if (!reader.ReadUint32(stateCount)) {
        outError = reader.Error();
        return false;
    }
    if (stateCount == 0) {
        outError = "pet has zero behavior states";
        return false;
    }
    pet.states.clear();
    pet.states.reserve(stateCount);
    for (std::uint32_t i = 0; i < stateCount; ++i) {
        BehaviorState state;
        if (!ReadState(reader, "states[" + std::to_string(i) + "]", state, outError)) {
            return false;
        }
        pet.states.push_back(std::move(state));
    }

    if (pet.canvasWidth <= 0 || pet.canvasHeight <= 0) {
        outError = "invalid canvas size";
        return false;
    }
    if (pet.visualScale <= 0.0) {
        outError = "invalid visualScale (must be > 0)";
        return false;
    }
    if (pet.id.empty()) {
        outError = "pet id must not be empty";
        return false;
    }
    if (!ValidateTargetStateIds(pet, outError)) {
        return false;
    }

    outPet = std::move(pet);
    return true;
}

bool LoadPetPackFromFile(const std::string& path, PetDefinition& outPet, std::string& outError) {
    std::ifstream file(path, std::ios::binary);
    if (!file) {
        outError = "could not open " + path;
        return false;
    }

    file.seekg(0, std::ios::end);
    const std::streamoff length = file.tellg();
    if (length < 0) {
        outError = "could not determine size of " + path;
        return false;
    }
    file.seekg(0, std::ios::beg);

    std::vector<std::uint8_t> buffer(static_cast<std::size_t>(length));
    if (!buffer.empty()) {
        file.read(reinterpret_cast<char*>(buffer.data()), length);
        if (!file) {
            outError = "failed reading " + path;
            return false;
        }
    }

    return LoadPetPackFromMemory(buffer.data(), buffer.size(), outPet, outError);
}

}  // namespace nimvlets::content
